import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import FilterButton  from './../src/components/atoms/filterButton';
import { Header } from './../src/components/organisms/header';
import StyledMainTitle  from './../styles/title';
import StyledMainContainer from './../styles/main';
import { StyledFilterButtonContainer } from '../src/components/atoms/filterButton/styles';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <StyledMainContainer>
        <StyledMainTitle>
            Milhões de filmes, séries e pessoas para descobrir. Explore já.
        </StyledMainTitle>

        <StyledFilterButtonContainer>
          <FilterButton title="Ação" imgUrl="https://cdn-icons-png.flaticon.com/512/174/174855.png"/>
          <FilterButton title="Aventura" imgUrl="https://cdn-icons-png.flaticon.com/512/174/174855.png"/>
          {/* <FilterButton title="Animação" imgUrl="https://cdn-icons-png.flaticon.com/512/174/174855.png"/>
          <FilterButton title="Comédia" imgUrl="https://cdn-icons-png.flaticon.com/512/174/174855.png"/>
          <FilterButton title="Crime" imgUrl="https://cdn-icons-png.flaticon.com/512/174/174855.png"/> */}
          {/* <FilterButton title="Documentário" imgUrl="https://cdn-icons-png.flaticon.com/512/174/174855.png"/> */}
        </StyledFilterButtonContainer>
       
      </StyledMainContainer>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
